# Generated by Django 4.2.3 on 2023-07-22 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0002_alter_portfolio_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='owner',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='userId',
            field=models.ForeignKey(db_column='userId', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
