# Generated by Django 4.2.3 on 2023-07-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_currencyallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyallocation',
            name='allocation',
        ),
    ]
