# Generated by Django 4.2.3 on 2023-07-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_remove_currencyallocation_allocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyallocation',
            old_name='currencyId',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='currencyallocation',
            old_name='portfolioId',
            new_name='portfolio',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='userId',
            new_name='user',
        ),
    ]
