# Generated by Django 4.2.3 on 2023-07-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_alter_currencysnapshot_currency'),
        ('portfolios', '0007_alter_currencyallocation_currency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyallocation',
            unique_together={('currency', 'portfolio')},
        ),
    ]
