# Generated by Django 4.2.3 on 2023-07-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('market_cap', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currentPrice', models.CharField(max_length=255)),
                ('lastPrice', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currencyId', models.ForeignKey(db_column='currencyId', on_delete=django.db.models.deletion.CASCADE, related_name='currencyPrice', to='currencies.currency')),
            ],
        ),
    ]
