# Generated by Django 4.2.3 on 2023-07-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currentPrice', models.CharField(max_length=255)),
                ('lastPrice', models.CharField(max_length=255)),
                ('market_cap', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='currency',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='volume',
        ),
        migrations.DeleteModel(
            name='CurrencyPrice',
        ),
        migrations.AddField(
            model_name='currencysnapshot',
            name='currencyId',
            field=models.ForeignKey(db_column='currencyId', on_delete=django.db.models.deletion.CASCADE, related_name='currencySnapshot', to='currencies.currency'),
        ),
    ]
