# Generated by Django 4.2.3 on 2023-07-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currencysnapshot_remove_currency_market_cap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencysnapshot',
            old_name='currentPrice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='currencysnapshot',
            name='lastPrice',
        ),
    ]
