# Generated by Django 4.2.3 on 2023-07-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_rename_currentprice_currencysnapshot_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencysnapshot',
            old_name='currencyId',
            new_name='currency',
        ),
    ]
