# Generated by Django 4.2.3 on 2023-07-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0008_alter_currencysnapshot_market_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencysnapshot',
            name='market_cap',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='currencysnapshot',
            name='volume',
            field=models.FloatField(),
        ),
    ]
