# Generated by Django 4.2.3 on 2023-07-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0009_alter_currencysnapshot_market_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencysnapshot',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
