# Generated by Django 4.2.3 on 2023-07-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0010_currencysnapshot_price_change_24h'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencysnapshot',
            old_name='price_change_24h',
            new_name='price_change_percentage_24h',
        ),
    ]
